### ISSUE TITLE
Choose 2 workable API's

### ISSUE THREAD

**Issue by FaithsCoding** [FaithsCoding/weather-i-go#2]
##USER STORY
As a team we want to choose 2 API's with no limitations so that we can use the data as JSON responses.

##ACCEPTANCE CRITERIA
Given that 2 free API's with no limitations are chosen when we use the API within our development we can use the responses to represent the users input.

**Comment by dexit** [comment]
TIcket API will be TIcketMaster

**Comment by Jake-Orch** [comment]
Weatherapi.com offers an API that meets our needs for its purpose

**Comment by dexit** [comment]
This is sorted !
